theme: jekyll-theme-minimal
title: My super cool website
description: My super cool description
logo: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/1200px-Cat_November_2010-1a.jpg
